name: Turbo
description:

inputs:
  turbo:
    description:
    default: run build

runs:
  using: composite
  steps:
    - name: Get last workflow run
      id: last-workflow-run
      if: ${{ startsWith(inputs.turbo, 'run ') }}
      uses: actions-pro/last-workflow-run@v1

    - name: Turbo
      shell: bash
      env:
        TURBO_CACHE_DIR: .turbo
      run: ${{ startsWith(inputs.turbo, 'run ') && steps.last-workflow-run.outputs.sha && format('echo -n "{0}" | tail -c +5 | xargs turbo run --filter=[{1}..HEAD]', inputs.turbo, steps.last-workflow-run.outputs.sha) || format('turbo {0}', inputs.turbo) }}
